version: '3.8'

x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '3'
  driver: json-file

networks:
  default:
    name: devnet

services:
  lotus:
    container_name: lotus
    image: ${IMAGE}
    entrypoint: ['/app/entrypoint-lotus.sh']
    ports:
      - "1234:1234"
      - "9090:9090"
    environment:
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
      - LOTUS_FEVM_ENABLEETHRPC=true
      - LOTUS_API_LISTENADDRESS=/dns/lotus/tcp/1234/http
      - LOTUS_LIBP2P_LISTENADDRESSES=/ip4/0.0.0.0/tcp/9090
      - LOTUS_SKIP_GENESIS_CHECK=_yes_
      - GENESIS_PATH=/var/lib/genesis
      - SECTOR_SIZE=8388608
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/lotus:/var/lib/lotus:rw
      - ./data/genesis:/var/lib/genesis:rw
      - ${FIL_PROOFS_PARAMETER_CACHE}:/var/tmp/filecoin-proof-parameters:rw

  lotus-miner:
    container_name: lotus-miner
    image: ${IMAGE}
    entrypoint: ['/app/entrypoint-lotus-miner.sh']
    depends_on:
      - lotus
    ports:
      - "2345:2345"
    environment:
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
      - LOTUS_API_LISTENADDRESS=/dns/lotus-miner/tcp/2345/http
      - LOTUS_API_REMOTELISTENADDRESS=lotus-miner:2345
      - LOTUS_SEALING_BATCHPRECOMMITS=false
      - LOTUS_SEALING_AGGREGATECOMMITS=false
      - LOTUS_SUBSYSTEMS_ENABLEMARKETS=false
      - LOTUS_SEALING_WAITDEALSDELAY=20s
      - LOTUS_SKIP_GENESIS_CHECK=_yes_
      - GENESIS_PATH=/var/lib/genesis
      - SECTOR_SIZE=8388608
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/lotus-miner:/var/lib/lotus-miner:rw
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/genesis:/var/lib/genesis:ro
      - ${FIL_PROOFS_PARAMETER_CACHE}:/var/tmp/filecoin-proof-parameters:rw

  boost:
    container_name: boost
    image: ${IMAGE}
    entrypoint: ['/app/entrypoint-boost.sh']    
    depends_on:
      - lotus
      - lotus-miner
    ports:
      - "8080:8080"
      - "1288:1288" # For the /metrics endpoint
      - "50000:50000" # Exposed libp2p port
    environment:
      - LOTUS_API_LISTENADDRESS=/dns/boost/tcp/1288/http
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
      - LOTUS_TRACING_ENABLED=true
      - LOTUS_TRACING_SERVICENAME=boostd
      - LOTUS_TRACING_ENDPOINT=http://tempo:14268/api/traces
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/boost:/var/lib/boost:rw
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner:/var/lib/lotus-miner:ro
      - ./data/sample:/app/public:rw

  booster-http:
    container_name: booster-http
    image: ${IMAGE}
    entrypoint: ['/app/entrypoint-booster-http.sh']
    ports:
      - "7777:7777"
    environment:
      - BOOST_PATH=/var/lib/boost
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/boost:/var/lib/boost:ro
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner:/var/lib/lotus-miner:ro
    labels:
      - "com.docker-tc.enabled=1"
      - "com.docker-tc.delay=10ms"

  booster-bitswap:
    container_name: booster-bitswap
    image: ${IMAGE}
    entrypoint: ['/app/entrypoint-booster-bitswap.sh']
    ports:
      - "8888:8888"
    environment:
      - BOOSTER_BITSWAP_REPO=/var/lib/booster-bitswap
      - BOOST_PATH=/var/lib/boost
      - LOTUS_PATH=/var/lib/lotus
      - LOTUS_MINER_PATH=/var/lib/lotus-miner
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/booster-bitswap:/var/lib/booster-bitswap:rw
      - ./data/boost:/var/lib/boost:ro
      - ./data/lotus:/var/lib/lotus:ro
      - ./data/lotus-miner:/var/lib/lotus-miner:ro
    labels:
      - "com.docker-tc.enabled=1"
      - "com.docker-tc.delay=10ms"
      